### ISSUE TITLE
Supporting .net standard

### ISSUE THREAD

**Issue by philippe-lavoie** [maurosampietro/UltraMapper#1]
I installed 0.2.15 inside a .Net standard project and it complaints that

Package 'UltraMapper 0.2.15' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

Is there a technical issue preventing this project from being usable from .Net Standard ?

**Comment by maurosampietro** [comment]
The project and nuget package target the .Net Framework
I can get to compile the project for .NET CoreApp, with no problem (never tested).
So i just need to make a project and a nuget package available for that target.

I'll make it available as soon as possible.

**Comment by maurosampietro** [comment]
I'm having a little issue with appveyor in deploying the package on github and nuget. I'm trying to solve with the help of appveyor support. Please be patient.

**Comment by maurosampietro** [comment]
A new nuget package is available on nuget.
Let me know if you encounter any difficulties, since my experience with .Net Standard is still limited.

**Comment by bugproof** [comment]
Doesn't work. I tried using it with .NET Core 3.1

**Comment by maurosampietro** [comment]
Download and compile the last version. It should compile for netstandard20 too.
A nuget package will be produced.
