### ISSUE TITLE
C#9 Features not supported

### ISSUE THREAD

**Issue by jameswoodley** [maurosampietro/UltraMapper#10]
Trying out UltraMapper and it failed to map to a record object, new in C# 9

For example
```
public class Scope
{
    public string Description { get; set; } = default!;
    public string Value { get; set; } = default!;
}

var mapper = new Mapper();
var map = mapper.Map<Scope>(otherObject);
```

works just fine, however
```
public record Scope(string Description, string Value);

var mapper = new Mapper();
var map = mapper.Map<Scope>(otherObject);
```

gives the error
```
Type 'Scope' does not have a default constructor (Parameter 'type')
```

It's very possible I've misunderstood the abilities of record, but they can be serialized so I therefore thought they should be able to be mapped?

**Comment by jameswoodley** [comment]
Just found also that if you map TO a record then it breaks equality

```
public record Record
{
    public string Value { get; init; }
}

var map1 = mapper.Map<Record>(otherObject);
var map2 = mapper.Map<Record>(otherObject);

map1.Equals(map2);  // <-- False
```

```
public record Record
{
    public string Value { get; init; }
}

var map1 = new Record { Value = otherObject.Value };
var map2 = new Record { Value = otherObject.Value };

map1.Equals(map2); // <-- True
```

**Comment by maurosampietro** [comment]
Hi,
I haven’t investigated records yet and at the time being they are not tested or supported.

I’ll take a look into it and let you know

**Comment by maurosampietro** [comment]
The following test passes OK.
Am i missing something?!

  [TestClass]
    public class Records
    {
        public record Record
        {
            public string Value { get; init; }
        }

        public class OtherObject
        {
            public string Value { get; set; }
        }

        [TestMethod]
        public void test()
        {
            var mapper = new Mapper();

            var otherObject = new OtherObject() { Value = "ciao" };

            var map1 = mapper.Map<Record>(otherObject);
            var map2 = mapper.Map<Record>(otherObject);

            Assert.IsTrue(map1.Equals(map2));

            var r1 = new Record { Value = otherObject.Value };
            var r2 = new Record { Value = otherObject.Value };

            Assert.IsTrue(r1.Equals(r2));
        }
    }
