### ISSUE TITLE
Method MissMatch Exception

### ISSUE THREAD

**Issue by zc910704** [maurosampietro/UltraMapper#11]
[GetNewInstanceWithReservedCapacity](https://github.com/maurosampietro/UltraMapper/blob/cceaf26f4d1e7b8b31118208ada00e45d7202304/UltraMapper/CodeGeneration/MappingExpressionBuilders/ReferenceTypeBuilders/CollectionTypeMappings/CollectionMapper.cs#L431)
function throw a  Method MissMatch Exception.

the reason is that `GetCountMethod ` assume type is a ICollection or Enumerable.
but in my case,It is a` Dictionary<string,float>`, so It's throw a exception. Is it reasonable?

**Comment by maurosampietro** [comment]
Dictionary<TKey,TValue> implements ICollection<T> though..
I would not expect this exception

**Comment by zc910704** [comment]
> Dictionary<TKey,TValue> implements ICollection<T> though.. I would not expect this exception
> […](#)
> On 6 Oct 2021, at 17:03, Zhang Chen ***@***.***> wrote: ﻿ GetNewInstanceWithReservedCapacity function throw a Method MissMatch Exception. the reason is that GetCountMethod assume type is a ICollection or Enumerable. but in my case,It is a Dictionary<string,float>, so It's throw a exception. Is it reasonable? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Yes. But the code use `typeof(System.Linq.Enumerable)` and `type.GetGenericArguments()[0] ` to Generate the GetCountMethod which `Dictionary` has two generic arguments, It should be KeyValuePair<string, float>, so it just throw exception when it call.I just curious why people haven't found this problom.  am I using it in a wrong way?

**Comment by zc910704** [comment]
thanks for point out how to use it. My problem is that I have a object like in the testcase and when I mapper it ,it just throw exception. maybe I describe something wrong.

**Comment by zc910704** [comment]
haha, Maybe my grammer mistake confused you. I thought the code should be easier like
```
if ( getCountProperty == null )
{
...
}
else
{
...
}
```
and I don't got what is the getLinqCount for.

**Comment by zc910704** [comment]
Got it, thanks
