### ISSUE TITLE
Making a shallow copies with cloned collections

### ISSUE THREAD

**Issue by InspiringCode** [maurosampietro/UltraMapper#2]
Is it possible to make a shallow copy of the following object, copying all properties and populating collections of the clone, but with the original item instances:

```
        public class SampleClass {
            public string DemoProperty { get; set; }

            public List<ItemClass> List { get; } = new List<ItemClass>();
        }
```

If not, do you know any library capable of this?

**Comment by maurosampietro** [comment]
No need for UltraMapper. Clone() function should do the job.
