### ISSUE TITLE
UltraMapper licensing

### ISSUE THREAD

**Issue by savornicesei** [maurosampietro/UltraMapper#9]
Hi,

I noticed that there's no license information in the repository so it's hard to decide if it can be used or not.

Thank you.

**Comment by maurosampietro** [comment]
Hello Simona,

The commons clause license will be applied. It’s free and you can build on top of it; but you can’t sell UltraMapper itself as a product, even if you modify it heavily.

**Comment by savornicesei** [comment]
So it can be used in/by a commercial product with the proper attribution?

Thank you.

**Comment by maurosampietro** [comment]
Yes

**Comment by maurosampietro** [comment]
LICENSE.md file attached. Copy its content or the whole file and include it in your projects.
